language: c
sudo: required
services:
  - docker

## We build on as many OCaml version as we can support. These versions
## are in fact tags for the ocaml/opam2 Docker image that we pull.

env:
  - TAG=4.07
  - TAG=4.06
  - TAG=4.05
  - TAG=4.04
  - TAG=4.03

script:
  - docker build
      --build-arg "TAG=$TAG"
      --build-arg "SWITCH=$SWITCH"
      --tag colisanr/lintshell:$TRAVIS_BRANCH
      .
